version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=
      - VERBOSE=2
    volumes:
      - './test.sh:/usr/local/bin/test.sh:ro'
    command: [ '/bin/sh', '/usr/local/bin/test.sh' ]