name: 'Delete Branch After Pull Request'

on:
  pull_request:
    types:
      - closed

jobs:
  get-changed-containers:
    timeout-minutes: 3
    runs-on: ubuntu-22.04

    steps:
      - name: Delete branch after merge
        if: ${{ github.event.pull_request.merged == true && github.head_ref != 'main' }}
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}"
